/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class ControleDeConta extends javax.swing.JFrame {



    public ControleDeConta() throws IOException {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnCentral = new javax.swing.JPanel();
        pnInferior = new javax.swing.JPanel();
        lbFraseMotivadora = new javax.swing.JLabel();
        lbCriador = new javax.swing.JLabel();
        pnTitulo = new javax.swing.JPanel();
        lbPrincipal = new javax.swing.JLabel();
        pnTabela = new javax.swing.JPanel();
        lbBanco = new javax.swing.JLabel();
        tfBanco = new javax.swing.JTextField();
        lbConta = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        lbAgencia = new javax.swing.JLabel();
        tfAgencia = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        tfSaldoInicial = new javax.swing.JTextField();
        btApagar = new javax.swing.JButton();
        brCriar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnCentral.setBorder(new javax.swing.border.MatteBorder(null));
        pnCentral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnInferior.setBackground(new java.awt.Color(0, 0, 255));
        pnInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnInferior.setPreferredSize(new java.awt.Dimension(360, 70));

        lbFraseMotivadora.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        lbFraseMotivadora.setForeground(new java.awt.Color(255, 255, 255));
        lbFraseMotivadora.setText("teste de digitação");
        pnInferior.add(lbFraseMotivadora);

        lbCriador.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbCriador.setForeground(new java.awt.Color(255, 255, 255));
        lbCriador.setText("Criador");
        pnInferior.add(lbCriador);

        pnTitulo.setBackground(new java.awt.Color(51, 51, 255));
        pnTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPrincipal.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbPrincipal.setText("Cadastrar Conta");
        pnTitulo.add(lbPrincipal);

        pnTabela.setBackground(new java.awt.Color(255, 255, 255));
        pnTabela.setLayout(new java.awt.GridLayout(8, 2, 25, 5));

        lbBanco.setText("Banco:");
        pnTabela.add(lbBanco);
        pnTabela.add(tfBanco);

        lbConta.setText("Conta:");
        pnTabela.add(lbConta);
        pnTabela.add(tfConta);

        lbAgencia.setText("Agência:");
        pnTabela.add(lbAgencia);
        pnTabela.add(tfAgencia);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ativa");
        pnTabela.add(jRadioButton1);

        jLabel1.setText("Saldo Inicial:");
        pnTabela.add(jLabel1);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Inativa");
        pnTabela.add(jRadioButton2);
        pnTabela.add(tfSaldoInicial);

        btApagar.setBackground(new java.awt.Color(255, 255, 255));
        btApagar.setText("Apagar");
        pnTabela.add(btApagar);

        brCriar.setBackground(new java.awt.Color(255, 255, 255));
        brCriar.setText("Criar");
        pnTabela.add(brCriar);

        btAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        pnTabela.add(btAlterar);

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        pnTabela.add(btSalvar);

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCentralLayout = new javax.swing.GroupLayout(pnCentral);
        pnCentral.setLayout(pnCentralLayout);
        pnCentralLayout.setHorizontalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(pnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCentralLayout.setVerticalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCentralLayout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE)
                    .addGroup(pnCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleDeConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleDeConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleDeConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleDeConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ControleDeConta().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ControleDeConta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brCriar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbAgencia;
    private javax.swing.JLabel lbBanco;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbCriador;
    private javax.swing.JLabel lbFraseMotivadora;
    private javax.swing.JLabel lbPrincipal;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnInferior;
    private javax.swing.JPanel pnTabela;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField tfAgencia;
    private javax.swing.JTextField tfBanco;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
